name: Cs2_alarmer
on:
  schedule:
    - cron: '0 22 * * *'  # UTC+8，对应中国每天早上六点
  workflow_dispatch:      # 开启手动触发，可以在github上提交任务

jobs:
  build:
    name: Run Python Script
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        id: run_script
        run: python cs_sync.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.protonmail.com # 电子邮件服务器地址
          server_port: 587  # 电子邮件服务器端口
          username: ${{ secrets.EMAIL_USERNAME }}  # 电子邮件账户用户名
          password: ${{ secrets.EMAIL_PASSWORD }}  # 电子邮件账户密码
          subject: "Python Script Result"
          body: ${{ steps.run_script.outputs.stdout }}
          from: luojicat@protonmail.com  # 发件人电子邮件地址
          to: 1791422575@qq.com  # 收件人电子邮件地址
